swagger: '2.0'
info:
  title: Node Content Management System
  description: API for Node Content Management System
  version: 1.0.0
host: localhost:3000
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: Users
    get:
      description: |
        Returns a list of users.  
        If a response has been truncated, a `206 Partial Content` status will be
        returned.
      parameters:
        - $ref: '#/parameters/page'
        - $ref: '#/parameters/per_page'
      responses:
        200:
          $ref: '#/responses/userListResponse'
        206:
          $ref: '#/responses/userListResponse'
definitions:
  user:
    title: User account
    type: object
    properties:
      username:
        type: string
      fullName:
        type: string
      email:
        type: string
        format: email
      role:
        type: string
      postCount:
        type: integer
  userList:
    title: User list
    type: array
    items:
      $ref: '#/definitions/user'
parameters:
  page:
    name: page
    in: query
    description: Result page to retrieve.
    type: integer
    default: 1
    minimum: 1
    maximum: 1000
  per_page:
    name: per_page
    in: query
    description: Number of items to return per page.
    type: integer
    default: 20
    minimum: 1
    maximum: 100
responses:
  userListResponse:
    description: List of users
    schema:
      $ref: '#/definitions/userList'
    headers:
      X-Total-Count:
        description: Total number of users matching query.
        type: number