swagger: '2.0'
info:
  title: Node Content Management System
  description: API for Node Content Management System
  version: 1.0.0
host: localhost:3000
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns a list of users
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/lastIdParam'
      responses:
        200:
          description: List of users
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
definitions:
  user:
    title: User account
parameters:
  limitParam:
    name: limit
    in: query
    description: Number of results to return per page
    type: integer
    default: 20
    maximum: 50
    minimum: 10
  lastIdParam:
    name: last_id
    in: query
    description: Starting point for results
    type: string
    format: byte